export const interestOptions = [
    { value: "Basketball", label: "Basketball" },
    { value: "Badminton", label: "Badminton" },
    { value: "Soccer", label: "Soccer" },
    { value: "Hiking", label: "Hiking" },
    { value: "Volleyball", label: "Volleyball" },
    { value: "Board Games", label: "Board Games" },
    { value: "Tennis", label: "Tennis" },
    { value: "Running", label: "Running" },
    { value: "Gaming", label: "Gaming" },
    { value: "Swimming", label: "Swimming" },
    { value: "Drinking", label: "Drinking" },
    { value: "Study", label: "Study" },
    { value: "Movies", label: "Movies" },
    { value: "Frat Parties", label: "Frat Parties" },
    { value: "Athletics", label: "Athletics" },
    { value: "Arts", label: "Arts" },
    { value: "Cooking", label: "Cooking" },

  ];