# This is the docker compose file for production
# Programmer: Ethan Lee
# This code is called when the user runs the script to use docker to set up the environment
version: "3.9"
services:

  front-end:
    build: 
      context: ./front_end
      dockerfile: Dockerfile
    hostname: front
    ports:
      - 3000:3000
    command: npm start
  
  back-end:
    build: 
      context: ./back_end
      dockerfile: Dockerfile
    hostname: back
    ports:
      - 8080:8080
    command: npm start
